refactor(modeling): remove use of slow Math.hypot
jscad/OpenJSCAD.org pull request #1099
Opened 2022-05-30 18:26 UTC by platypii

It turns out that `Math.hypot` is much slower than `Math.sqrt`, as pointed out by @briansturgill in #1095

I liked using hypot for increased accuracy, and nicer to read. But since it is slower, I think it should go away.

I had to remove the tests for accuracy on very small, and very large numbers (1e200+).

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

2022-05-30 18:42 UTC, hrgdavor reviewed
looks good

2022-05-30 21:19 UTC, z3dev commented
@platypii sorry. I'm not going for this without a good reason. For places where performance matters then the larger function can opt for using sqrt(). I think we should open an issue with gl matrix, and ask why that library uses hypot()

2022-05-30 22:18 UTC, platypii commented
@z3dev that's fair. I'll see if I can measure the speed difference in real models.

2022-05-30 23:09 UTC, platypii commented
Changing from `hypot` to `sqrt` makes a significant 30%+ speed up on unions. I think it's worth considering the change.

|  | hypot | no hypot | improvement |
| --- | --- | --- | --- |
| disjoint (x=4) | 480ms | 480ms | 0% |
| touching (x=2) | 8500ms | 5800ms | 31.8% |
| overlap (x=1) | 8900ms | 5850ms | 34.3% |
| inside (x=0) | 7300ms | 4800ms | 34.2% |

<details>
<summary>Test script</summary>

```js
const jscad = require('@jscad/modeling')
const { sphere } = jscad.primitives
const { union } = jscad.booleans

const main = () => {
  const segments = 100
  const x = 1
  let s1 = sphere({ segments })
  let s2 = sphere({ segments, center: [x, 0, 0] })
  const startTime = performance.now()
  const out = union(s1, s2)
  console.log(`Union time ${performance.now() - startTime} ms`)
  return out
}

module.exports = { main }
```
</details>

2022-05-31 07:29 UTC, hrgdavor commented
that is massive, definitely worth changing

2022-05-31 09:33 UTC, z3dev commented
> Changing from `hypot` to `sqrt` makes a significant 30%+ speed up on unions. I think it's worth considering the change.
> 
> hypot	sqrt	improvement
> disjoint (x=4)	480ms	480ms	0%
> touching (x=2)	8500ms	5800ms	31.8%
> overlap (x=1)	8900ms	5850ms	34.3%
> inside (x=0)	7300ms	4800ms	34.2%
> Test script

I'm not saying that the replacement shouldn't be done. I'm saying that we should be selective about the replacement. Booleans may benefit but we don't want to create other issues.

We should do some research, and ask the gl matrix geeks. And try to understand the math completely.

2022-05-31 17:23 UTC, platypii commented
https://github.com/toji/gl-matrix/issues/446

2022-06-04 05:00 UTC, z3dev commented
FYI, here's the js-core implementation of hypot()

https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.math.hypot.js

2022-06-05 04:23 UTC, platypii commented
The core-js polyfill implementation is somehow even slower than Math.hypot despite using sqrt. :vomiting_face: 

| environment | hypot | sqrt | core-js |
|-------------|-------|------|-------|
| chrome      | 235ms | 12ms | 328ms |
| firefox     | 64ms  | 12ms | 160ms |
| safari      | 390ms | 74ms | 1830ms |
| node        | 248ms | 11ms | 370ms |

2022-06-07 11:34 UTC, z3dev requested changes

2022-06-07 11:34 UTC, z3dev commented on packages/modeling/src/maths/mat4/rotate.js
> +  if (Math.abs(lengthSquared) < EPSILON) {
I suggest that we use the EPS for normals, then we know that this function works for calculations with normals.

2022-06-07 11:34 UTC, z3dev commented on packages/modeling/src/maths/mat4/fromRotation.js
> +  if (Math.abs(lengthSquared) < EPSILON) {
Let's use the EPS for normals.

2022-06-10 09:35 UTC, z3dev approved these changes
@platypii thanks again. Let's see if the general user community feels any performance improvement.

2022-06-10 09:36 UTC, merged