add chinese translate to desktop/locales and web/locales
jscad/OpenJSCAD.org pull request #1123
Opened 2022-07-19 10:21 UTC by jobinson99

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

2022-07-21 11:58 UTC, platypii commented on packages/desktop/locales/en.json
> +  "chinese":"Chinese",
language should be lowercase to match other languages

2022-07-24 00:01 UTC, z3dev requested changes

2022-07-24 00:01 UTC, z3dev commented on packages/web/locales/zh.json
> +  "editorCommand":"Editor command",
Hmm... I would guess that an equivalent Chinese phrase exists.

2022-07-24 00:02 UTC, z3dev requested changes
@jobinson99 Thanks for these nice additions. There are a few small requests.

2022-07-24 11:52 UTC, z3dev approved these changes
@jobinson99 SUPER! Thanks for making those changes. I hope this builds more interest from the folks in China (and other countries)

P.S. You can 'resolve' any requests after making changes. 😃

2022-07-25 23:10 UTC, z3dev approved these changes
@jobinson99 thanks for the updates. this looks fine now.

2022-07-25 23:12 UTC, merged