fix 1178 transparent object overlap solid objects
jscad/OpenJSCAD.org pull request #1179
Opened 2022-12-22 19:06 UTC by hrgdavor

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

this fixes #1178 by removing code I added previously for transparent entities

2022-12-22 21:12 UTC, platypii commented
I'm trying to test this locally, but I'm not seeing the same thing you are with transparency. And when I checkout this branch, I'm not seeing any change in behavior? Can you give an example, and maybe screenshots of JSCAD (not your prototype) showing the difference?

I tried:

```js
const main = () => {
  const s1 = colorize([0.8, 0.8, 0, 0.4], cube({ }))
  const s3 = colorize([0, 0.1, 0.9, 0.6], sphere({ center: [1.2, 0.2, 1] }))
  return [s1, s3]
}
```

And got:
![Screenshot at 2022-12-22 13-07-20](https://user-images.githubusercontent.com/1766297/209226741-14d1bb60-691c-441b-94c5-1af3445da617.png)

2022-12-22 21:54 UTC, hrgdavor commented
ok, nice test. looks like more things needed fixing because I probably worked around the issues in my prototype.

current jscad
![image](https://user-images.githubusercontent.com/2480762/209230895-5061f4a9-ce6d-4e22-9595-e0b45de09b0d.png)

with fix
![image](https://user-images.githubusercontent.com/2480762/209231052-c3528324-90eb-4a37-b12f-f1102f7271d7.png)

code:
```js

const jscad=require('@jscad/modeling')
const {colorize} = jscad.colors
const {sphere,cube} = jscad.primitives

const main = () => {
  const s1 = colorize([0.8, 0.8, 0, 0.5], cube({ }))
  const s3 = colorize([0, 0.1, 0.9], sphere({ center: [1.2, 0.2, 1] }))
  return [s1, s3]
}

module.exports = {main}
```

2022-12-22 22:05 UTC, platypii submitted a review, later dismissed
Beautiful! This is a significant improvement in transparency quality! Thanks @hrgdavor 

![Screenshot at 2022-12-22 14-04-27](https://user-images.githubusercontent.com/1766297/209233781-641f7b62-a2f7-484a-b365-ac83c4f7157a.png)

2022-12-23 00:26 UTC, platypii approved these changes

2022-12-24 08:18 UTC, z3dev requested changes
@hrgdavor looks like a very nice fix. i just have one small suggestion. then this is ready to go.

2022-12-24 08:18 UTC, z3dev commented on packages/utils/regl-renderer/src/rendering/commands/drawMesh/index.js
> +  const { geometry, dynamicCulling, useVertexColors, color, visuals } = Object.assign({}, defaults, params)
hmm... it seems that we never had a 'default' value for transparent. let's assign a proper 'default' for visuals. maybe {}?

2022-12-24 12:56 UTC, z3dev approved these changes
@hrgdavor thanks again for the nice fixes!

2022-12-24 12:58 UTC, merged

2022-12-24 13:04 UTC, hrgdavor commented
np, I introduced this bug 😄 in #1060