build(all): changes to packages and rollup in preparation for prerelese
jscad/OpenJSCAD.org pull request #1281
Opened 2023-08-20 02:16 UTC by z3dev

### WORK IN PROGRESS
### DO NOT MERGE

These changes update the various packages in preparation for pre-releases of V3. The changes include:
- package changes for distributing UMD and ES libraries
- rollup changes to include all dependencies and minify the package

**NOTE: There are no code changes.**

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Does your submission pass tests?

2023-08-20 02:19 UTC, z3dev commented
@platypii @hrgdavor @SimonClark 

some quick questions...

the packages are being reworked slightly to provide a list of contributors. should the list contain email/url or just names? or nothing at the package level? or a BIG list of contributors are the project level? note that most of the lists are out of date

2023-08-20 06:26 UTC, hrgdavor commented
It is nice to keep a mention of people that contributed. Big list of contributors at project level is fine, I think is tedious to provide it for each package. 
for the contributor inof, keep what you have now, and those that want to change the info can provide a PR. For me personally, at this point in time a link to github profile is fine.

2023-08-20 06:27 UTC, hrgdavor submitted a review, later dismissed
looks good :)

2023-08-21 05:43 UTC, platypii approved these changes
Looks good, tested locally. No strong opinion on the contributors but seems fine

2023-08-21 05:54 UTC, platypii requested changes

2023-08-21 05:54 UTC, platypii commented on packages/utils/array-utils/package.json
> +    "test:tsd": "tsd",
This line is causing the tests to fail, because there are no type tests for `array-utils`. I suggest removing this line.
```suggestion
```

2023-08-27 01:09 UTC, z3dev commented
@platypii @hrgdavor I'm going to stop here as there are lots of changes to each of the packages. That will make the review easy. I'll continue on with the rollup configurations in part 2.

2023-08-27 02:58 UTC, platypii approved these changes
Good changes :+1:

2023-08-27 04:00 UTC, merged