Update orbitControls.js
jscad/OpenJSCAD.org pull request #735
Opened 2020-11-17 23:30 UTC by hrgdavor

### All Submissions:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

a small fix that modifies pan so it is scaled based on current zoom (distance camera<->eye).

There is a comment near my change that somebody left there
```
  // TODO scale by the correct near/far value instead of 1000 ?
  // const planesDiff = camera.far - camera.near
```

but when I inspected near and far, it was the same regardless of zoom. Maybe this is related to some other aspect.

It is a simple improvement, please test if you find problems with the change.

2020-11-17 23:39 UTC, hrgdavor commented
Also works better on mobile, and is more aligned with fingers than current jscad.xyz

2020-11-20 01:56 UTC, z3dev requested changes
Just a small change requested to remove comments.

I tried this on all browsers on MacOS and iOS. Works really nice. SUPER JOB!

2020-11-20 01:56 UTC, z3dev commented on packages/utils/regl-renderer/src/controls/orbitControls.js
>    // TODO scale by the correct near/far value instead of 1000 ?
I think this fix addresses this TODO, so let's remove the comments.

2020-11-20 09:04 UTC, z3dev approved these changes
Looks nice!
Thanks for the late change.

2020-11-20 11:47 UTC, merged