reorg(web): integrated most-gestures into web package
jscad/OpenJSCAD.org pull request #832
Opened 2021-05-11 05:28 UTC by z3dev

These change integrate most-gestures into the web package, eliminating the need for the most-gesture package (maintained outside of JSCAD)

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

2021-05-11 05:33 UTC, z3dev commented
@SimonClark please review. i decided to bring most-gestures into the web package, as this makes maintenance easier. the code has already gone through changes due to lint/code standards.

2021-05-15 00:55 UTC, mister-jscad requested changes
Besides the requested change...

1. Add LICENSE from original package
2. Enable test script for web package

2021-05-15 00:55 UTC, mister-jscad commented on packages/web/src/most-gestures/presses.js
> +  // const moves$ = merge(mouseMoves$, touchMoves$)
unused? then let's remove it.

2021-05-15 01:13 UTC, mister-jscad approved these changes
OK. Good to go!

2021-05-15 04:30 UTC, merged