Fix color serialization and deserialization
jscad/OpenJSCAD.org pull request #852
Opened 2021-06-02 06:01 UTC by z3dev

These changes correct the serialize and deserialize of geometries.

In general, colors are serialized using:
- color on geometry converted to color on shape (external format)
- color on polygon converted to color on face (external format)

In general, colors are deserialized using:
- color on shape to color on geometry
- color on face to color on polygon

There are related fixes to modeling, as the new modifiers (snap and triangulate) were not maintaining the colors assigned to polygons.

There is also a fix to the CLI, to allow serialization parameters to be passed through. This allows serialization and deserialization options to be specified on the command line. Such as:
- target geometry
- units
- segments

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

Additional testing was conducted with deserialization of all sample files to geometry.
Additional testing was conducted with 2D and 3D geometries to shapes (all available external formats)

2021-06-02 06:05 UTC, z3dev reviewed
Changes as expected.

2021-06-04 05:12 UTC, mister-jscad requested changes
Food for thoughts... and changes.

2021-06-04 05:12 UTC, mister-jscad commented on packages/cli/src/generateOutputData.js
> +    source = conversionTable[inputFormat]({ source, params, options: deserializerOptions })
do deserializers have an 'params' option?

2021-06-04 05:12 UTC, mister-jscad commented on packages/io/amf-serializer/README.md
> +- serialization of 3D geometry (geom3) to AMF object (a unique mesh containing both vertices and volumes)
These comments in the jsdoc would be nice as well.

2021-06-04 05:35 UTC, mister-jscad approved these changes
Changes look good.

2021-06-04 05:44 UTC, merged