Fix 876 expand v2
jscad/OpenJSCAD.org pull request #898
Opened 2021-08-06 20:54 UTC by hrgdavor

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

this is a second attempt at fixing #876 
 - bonus fixed a bug that would crash retesellate

#877 was too complicated. instead of stopping right away that version when noticed the stop condition tried then to use other polygons from the list to do the splitting. This was wrong as it looks like it does not matter which one is chosen is stop condition is met, it will be met for all of them for sure. Hence it is enough to check just one of them.

@z3dev you noticed correctly that #877 one was fishy. This one does not affect tests, it just fixes the issue so I am sure it will be much easier to review :)

2021-08-10 01:53 UTC, z3dev commented
@hrgdavor Thanks. This looks more interesting.

Is this ready for review? There are still a few debugging statements.

2021-08-10 07:35 UTC, hrgdavor commented
@z3dev it is now ready for review. Thnx for noticing those. You may notice I like to rush things :).

When u have time, check my other PR's if you have suggestions. (I know you will not be able to properly test some of them until you get back)

Since I can't nag you on discord, here is small update on some of things in progress

I am working on few things in paralel, so there will be more PR's ... latest effort is 3mf serializer (it is exporting nicely and also embeds preview png )
![image](https://user-images.githubusercontent.com/2480762/128825737-12a670d4-b1b8-483a-83ec-86bf2822091b.png)
Those marked with red numbers are the 3mf export.

One nice thing aabout 3mf is that it supports instancing (declare geometry once and reference in the final output). 

Also instancing greatly helps performance ... I was able to get 32x32x32 initial render of the model down to 20ms (30 thousand logos)
![image](https://user-images.githubusercontent.com/2480762/128826492-06bea77f-0a83-4852-b248-62f28023d2f0.png)
(regl renderer starts to struggle with grid larger than 5x5x5)


I also went through old issues and found metaballs. So I converted them to V2 code 
![image](https://user-images.githubusercontent.com/2480762/128826826-aa16d1ae-c189-4be9-b0e4-bc7b068b3e6f.png)

![image](https://user-images.githubusercontent.com/2480762/128826864-023cb37e-052c-4667-81a1-bf6c299f0c00.png)

2021-09-04 04:45 UTC, z3dev commented
I tested a little with these changes. The change to reTesselateCoplanarPolygons() corrects issues, and allows the expansion to complete. But the results of the expansion are still very poor.

It seems that there's something very wrong with the expandShell() function, which does the 3D geometry expansion.

![issue876](https://user-images.githubusercontent.com/8969165/132082679-546ea2ad-50d6-4e76-9cde-9b06eac69a94.png)

I think the example given in #876 will help to debug and fix this issue.

2021-09-04 06:51 UTC, hrgdavor commented
The fix to reTesselateCoplanarPolygons is just a sidefix so it does not produce invalid results.

The actuall fix aimed by this PR is about the Node.js and adding a stop condition to prevent infinite loop.

The question here is if that stop condition is enough, for this PR., and if expandShell() need another issue and another fix.

If this PR needs further improvement, pls give some direction :)

2021-09-04 08:04 UTC, z3dev commented
> The actual fix aimed by this PR is about the Node.js and adding a stop condition to prevent infinite loop.

I found that the fix to reTesselateCoplanarPolygons() was enough, and corrected the infinite loop.

Either way, there are not definite test cases for either of the fixes. So, it needs some more research on the real issue.

2021-09-04 08:06 UTC, hrgdavor commented
I have just noticed I named the PR "Fix 876 expand v2" so yes, direction may be ok, but needs more research.
Could you give me an example that is messed put like that one in the picture ?

2021-09-04 08:33 UTC, hrgdavor commented
The more I am looking how the expand is implemented, the less I like it. I need your help to differentieate CSG issue here from expand issues.

I would actually like to rename this PR or make another one with current fixes `Fix infinite loop in CSG subdivision and reTesselateCoplanarPolygons empty polygons`. 

I am not liking the approach made in this expand function, the performance implications and also the end result is messy, so I am not sure it is worth fixing.

2021-09-04 08:40 UTC, z3dev commented
> I am not liking the approach made in this expand function, the performance implications and also the end result is messy, so I am not sure it is worth fixing.

It's definitely one UGLY function. Although, I must give credit because this was written long long ago when the math was pretty iffy.

I'll try to knock together a nice little test case for the expand(), and try to make it break big time. I'll post back once complete.

There may be some related issue to the boolean functions, as there have been cases of infinite loops in the past. If you can find a test cases for these fixes then that would awesome.

2021-09-04 08:50 UTC, hrgdavor commented
I produce ugly code all the time, so I do not have an issue calling other ppl's code ugly :D and I am fine with ugly code that works.

The ugly code that sort of works usually ok, and if it does something that it is really needed, it then leads to more ideas as issues are exposed after actual use/abuse. So I am grateful someone implemented this version of expand, even though it is not perfect, it is mostly usable and allows us to see if it is something worth exploring further and improving.

I will look through issues if there are other examples of booleans hanging,, and ofc, if u find some, let me know.

2021-09-04 10:25 UTC, hrgdavor commented
There is another example from #598 that also crashes openjscad.xyz but demostrates that this fix is not complete as it leaves artifacts isntead of crashing.
The stop condition is good to prevent crash, but needs to be investigated to prevent from leaving holes

Here is v2 version of the code
```
const jscad = require('@jscad/modeling')
const { measureBoundingBox } = jscad.measurements
const { cube, cuboid, sphere, cylinder } = jscad.primitives
const { translate, rotate } = jscad.transforms
const { colorize } = jscad.colors
const { union, subtract, intersect } = jscad.booleans

function main() {
    let out = [
        translate([5, 5, 5], sphere({ radius: 5, segments: 32 })),
        translate([0, 0, 10], cube({ size: 10 })),
        translate([5, 5, 20], cylinder({ startRadius: 1, endRadius: 5, height: 10, segments: 16 }))
    ]
    
    out = union(out);
    out = bendObj(out, 20, 5);
    out = union(out)
    return out
}

const bendObj = (obj, objRadius, segments = 1) => {
    const slices = [];

    if (segments === 1) { 
        slices.push(bend(obj, objRadius));
    } else {
        const objSize = measureBoundingBox(obj);
        const objW = Math.abs(objSize[0][0] - objSize[1][0]);
        const objD = Math.abs(objSize[0][1] - objSize[1][1]);
        const objH = Math.abs(objSize[0][2] - objSize[1][2]);
        const objSliceHeight = objH / segments;

        for (let x = 0; x < segments; x++) {
            const bentObj = bend(
                intersect(
                    translate([0, 0, x * -objSliceHeight], obj),
                    translate([-5, -5, 0], cuboid({ size: [objW + 10, objD + 10, objSliceHeight] }))
                ),
                objRadius
            );
            const angleAlpha = (x * objSliceHeight) / objRadius;

            slices.push(translate([0, -objRadius, 0], rotate([angleAlpha, 0, 0], translate([0, objRadius, 0], bentObj))));
        }
    }

    return slices;
};

const bend = (obj, objRadius) => { 
    const csg = jscad.geometries.geom3.create();

    obj.polygons.forEach((polygon) => {
        const vertices = [];

        polygon.vertices.forEach((vertex) => {
            const angleAlpha = vertex[2] / objRadius;
            const newRadius = objRadius + vertex[1];
            const posY = Math.cos(angleAlpha) * newRadius - objRadius;
            const posZ = Math.sin(angleAlpha) * newRadius;

            vertices.push([vertex[0], posY, posZ]);
        });

        csg.polygons.push({vertices});
    });

    csg.isCanonicalized = false;
    csg.isRetesselated = false;
    return csg;
};

module.exports = {main}
```

2021-09-04 10:36 UTC, hrgdavor commented
Original object after union
![image](https://user-images.githubusercontent.com/2480762/132091429-c8242e08-8886-4564-8a07-11afaadee899.png)

The object after bend function (has holes from the function, that are not fault of booleans):
![image](https://user-images.githubusercontent.com/2480762/132091498-e57f3f0b-f5b1-4c3d-a05a-af0efa4694a5.png)

The object after union, with 2 extra artefacts
![image](https://user-images.githubusercontent.com/2480762/132091542-0d525456-d44a-459e-a2aa-8071b9240b59.png)

2021-09-04 11:37 UTC, hrgdavor commented
After debugging the code and dumping the polygons that are part of the stop condition that was added, it is clear at least for this exact case that they are not the part of the issue, as all 3 `1,2,3` instances are somewhere else where object seems to be ok. The artefacts from union are `4,5`

![image](https://user-images.githubusercontent.com/2480762/132093042-35c7fc6f-2348-4474-a2f1-6c43e145af05.png)

2021-09-04 11:43 UTC, hrgdavor commented
disabling retesselate fixes one artefact.
![image](https://user-images.githubusercontent.com/2480762/132093212-617201c3-5b79-48bf-b67d-84aa598d5e61.png)

2021-09-06 07:05 UTC, hrgdavor commented
@z3dev could you please review again. it looks like without changing this PR issues are solved by using generalize after the user function that does bending and before union.

```js
out = scad.modifiers.generalize({snap:true,simplify:false}, out)
```

2021-09-16 04:23 UTC, z3dev commented
@hrgdavor these changes are really good. i especially like the changes to the Node.js code as there have been lots of issues with infinite loops.

however, a simple test case would be good to have. let's continue to search for one.

2021-09-19 21:52 UTC, hrgdavor commented
Not sure what kind of test case is needed here, as it is bit hard to make test to force infinite loop.
The fix seems to improve the booleans to prevent at least this case that causes infinite loop.

I does not fix #907 but also does not make it worse.

It would be good to merge this and continue working out the cause of those artifacts in #907 in a separate PR

2021-09-22 19:03 UTC, hrgdavor commented
I have added the test that makes expand go into infinite loop (Node.js actually)

it failed on master branch 
```
@jscad/modeling:   × Timed out while running tests
@jscad/modeling:   1 tests were pending in src\operations\expansions\expandGeom3.test.js
@jscad/modeling:   ( ) operations » expansions » expandGeom3 » expand survives bug 876
```

but works on this PR

@z3dev pls review

2021-09-25 02:17 UTC, z3dev requested changes
OK. I'm fine with this test.

Just a few small changes.

2021-09-25 02:17 UTC, z3dev commented on packages/modeling/src/operations/expansions/expandGeom3.test.js
> +const { expand } = require('./index')
instead of using 'expand', let's test with expandGeom3

`const expandGeom3 = require('./expandGeom3')`

2021-09-25 02:17 UTC, z3dev commented on packages/modeling/src/operations/expansions/expandGeom3.test.js
> +test('expand survives bug 876', async (t) => {
title change... 'expandGeom3: expand completes properly, issue 876'

2021-09-25 07:50 UTC, hrgdavor commented
Fixed latest comments, @z3dev pls review :)

2021-09-26 01:33 UTC, z3dev approved these changes
Super. Thanks for the last set of changes!

2021-09-26 01:35 UTC, merged